# Generated by Django 4.2.6 on 2023-10-20 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='활동 아이디')),
                ('intro', models.CharField(blank=True, max_length=500, null=True, verbose_name='소개글')),
                ('profile_img', models.ImageField(default='user/DefaultProfileImage.png', upload_to='user/profile_img/%Y/%m/%d', verbose_name='프로필 이미지')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('subscribe', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='구독')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
