# Generated by Django 4.2.6 on 2023-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(upload_to='user/profile_img/%Y/%M/%D/', verbose_name='프로필 이미지'),
        ),
    ]
